/**
 * @file Rule06_AiGeneratedMixedData.js
 * @description ANOM_006: AI-Generated vs Human-Confirmed Mixed Data (生成资料与人工确认混杂)
 * @module anomaly/rules/Rule06_AiGeneratedMixedData
 * @license MIT
 */

'use strict';

const RULE_ID = 'ANOM_006_AI_HUMAN_MIXED_DATA';
const SEVERITY = 'MEDIUM';
const CATEGORY = 'QUALITY_GOVERNANCE';

/**
 * Detects AI generated content mixed in canonical paths without verification or status contradictions.
 * @param {import('../../db/DatabaseManager')} dbManager
 * @param {string} [scanSessionId='default']
 * @param {object} [options={}]
 * @returns {Array<object>} Array of detected anomaly objects
 */
function detect(dbManager, scanSessionId = 'default', options = {}) {
  const db = dbManager.getDatabase();
  const anomalies = [];

  const sql = `
    SELECT 
      sf.id,
      sf.relative_path,
      sf.file_name,
      sf.source_category,
      sf.status,
      sf.review_status,
      sf.frontmatter_raw,
      sf.frontmatter_json,
      e.entity_id,
      e.canonical_name,
      e.review_status AS entity_review_status
    FROM source_files sf
    LEFT JOIN entities e ON e.source_file_id = sf.id
    WHERE sf.status != 'deleted'
  `;

  const rows = db.prepare(sql).all();

  const isCanonicalPath = (p) => /(^|\/)(01_worldview|01_世界观|canonical|canon|planets\/canonical)(\/|$)/i.test(p);
  const aiWatermarkRegex = /as an ai language model|generated by gpt|作为一名人工智能|请生成|prompt:\s*|ai_generated:\s*true/i;

  for (const row of rows) {
    const relPath = row.relative_path || '';
    const rawFm = row.frontmatter_raw || '';
    const reviewStatus = row.review_status || 'unreviewed';
    let isAiFm = false;
    try {
      if (row.frontmatter_json) {
        const parsed = typeof row.frontmatter_json === 'string' ? JSON.parse(row.frontmatter_json) : row.frontmatter_json;
        if (parsed && (parsed.ai_generated === true || parsed.ai_generated === 'true')) {
          isAiFm = true;
        }
      }
    } catch (_) {}
    const hasAiWatermark = aiWatermarkRegex.test(rawFm) || isAiFm;

    let anomalyReason = null;
    let detectedMarker = null;

    // Case 1: Unreviewed or AI generated file located in Canonical / Canon directory
    if (isCanonicalPath(relPath) && (reviewStatus === 'unreviewed' || reviewStatus === 'ai_generated' || reviewStatus === 'draft' || reviewStatus === 'pending' || isAiFm)) {
      anomalyReason = `File is in canonical directory but review_status is '${reviewStatus}'${isAiFm ? ' and has ai_generated frontmatter' : ''}`;
      detectedMarker = `Canonical path with unconfirmed status: ${reviewStatus}`;
    }
    // Case 2: File marked confirmed/finalized but contains raw AI watermarks
    else if ((reviewStatus === 'confirmed' || row.status === 'finalized' || row.status === 'active') && hasAiWatermark) {
      anomalyReason = `File is marked '${reviewStatus}/${row.status}' but contains AI generation watermark`;
      const match = rawFm.match(aiWatermarkRegex);
      detectedMarker = match ? match[0] : (isAiFm ? 'ai_generated frontmatter' : 'AI watermark detected');
    }
    // Case 3: Review status is explicitly ai_generated without review in production category
    else if (reviewStatus === 'ai_generated' && (row.status === 'finalized' || row.status === 'active') && !isCanonicalPath(relPath)) {
      anomalyReason = `Active/finalized file has unvetted review_status='ai_generated'`;
      detectedMarker = `review_status = 'ai_generated'`;
    }

    if (anomalyReason) {
      anomalies.push({
        scan_session_id: scanSessionId,
        anomaly_rule_id: RULE_ID,
        anomaly_type: CATEGORY,
        severity: SEVERITY,
        title: `AI/Human data governance issue in '${relPath}'`,
        message: `File '${relPath}': ${anomalyReason}.`,
        affected_file_paths_json: [relPath],
        affected_entity_ids_json: row.entity_id ? [row.entity_id] : [],
        details_json: {
          fileId: row.id,
          relativePath: relPath,
          status: row.status,
          reviewStatus: row.review_status,
          entityReviewStatus: row.entity_review_status,
          detectedMarker,
          reason: anomalyReason
        },
        suggested_action: `Review and verify content manually, or relocate file to 'Drafts/' directory until confirmed.`,
        is_resolved: 0
      });
    }
  }

  return anomalies;
}

module.exports = {
  id: RULE_ID,
  ruleId: RULE_ID,
  identifier: 'AI_HUMAN_MIXED_DATA',
  name: 'AI-Generated vs Human-Confirmed Mixed Data',
  severity: SEVERITY,
  category: CATEGORY,
  detect
};
